### ISSUE TITLE
The revolt side of the bridge doesn't properly bridge quotes

### ISSUE THREAD

**Issue by ghost** [Jan0660/Taco#3]
What was said on Discord:

![image](https://user-images.githubusercontent.com/68067125/144678679-0fedd134-9172-4837-a2bc-29dea7c9e631.png)

How it bridged to Revolt:

![image](https://user-images.githubusercontent.com/68067125/144678721-29771656-8e28-4a23-896d-71e9531279cb.png)

**Comment by Jan0660** [comment]
This is not an issue with the bridge itself. It's because Revolt follows [the CommonMark spec](https://spec.commonmark.org/0.30/#block-quotes) for block quotes and Discord does not. I'll try to implement a work-around for this later today.
